[package]
name = "rosettacontracts"
version = "0.1.0"
edition = "2023_11"

[[target.starknet-contract]]
casm = true
sierra = true


[dependencies]
starknet = "2.8.2"
openzeppelin = "0.17.0"
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
alexandria_numeric = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.31.0" }
assert_macros = "2.8.2"