[package]
name = "rosettaaccounts"
version = "0.1.0"
edition = "2023_11"

[[target.starknet-contract]]
casm = true
sierra = true


[dependencies]
starknet = ">=2.7.0-rc.0"

[dev-dependencies]
cairo_test = "2.7.0-rc.0"
