[package]
name = "rosettacontracts"
version = "0.1.0"
edition = "2024_07"

[[target.starknet-contract]]
casm = true
sierra = true

[scripts]
test = "snforge test"

[dependencies]
starknet = "2.10.1"
openzeppelin_utils = "1.0.0"
openzeppelin_token = "1.0.0"

[dev-dependencies]
snforge_std = "0.38.0"
assert_macros = "2.10.1"