name: Lint build and test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  lint_build_and_test:
    name: Lint build and test
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: software-mansion/setup-scarb@v1
       with:
         scarb-version: "2.10.1"
     - uses: foundry-rs/setup-snfoundry@v3
       with:
         starknet-foundry-version: "0.38.0"
     - name: Cairo lint
       run: scarb fmt --check
     - name: Cairo build
       run: scarb build
     - name: Cairo test
       run: scarb test
