name: Lint build and test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint_build_and_test:
    name: Lint build and test
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Check Scarb Version
        if: ${{ !vars.SCARB_VERSION }}
        run: |
          echo "SCARB_VERSION is not set."
          exit 1
          
      - uses: actions/checkout@v3

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "${{ vars.SCARB_VERSION }}"

      - name: Cairo lint
        run: scarb fmt --check

      - name: Cairo build
        run: scarb build

      - name: Cairo test
        run: scarb test
